import { NextResponse } from "next/server";

// ───────────────────────────────────────────────────────────────────────────
// School API — Jack's live class schedule.
//
// SOURCE OF TRUTH: the published schedule app at
// https://wingdigital26-maker.github.io/schedule/
//
// That page is generated by schedule-hub/build.py, which keeps every schedule
// inside a marked block in the HTML:
//
//   /* ==DATA:START== */  ... const COURSES = [ ... ]  /* ==DATA:END== */
//
// So the published page IS the data file. We fetch the live page and parse the
// block out of it. Nothing is copied into this repo: if Jack edits the markers
// and runs build.py, the next request here sees the new courses with no step
// on this side.
//
// Why fetch the published page rather than read C:\Users\wjack\schedule-hub:
// the OS runs on Vercel with the PC off, where that path does not exist, and
// the local file can also be ahead of what is actually published. The live URL
// is the thing Jack and anyone else actually sees.
//
// STALENESS: GitHub Pages sends Cache-Control: max-age=600, so a plain fetch
// could serve ten-minute-old HTML from an edge cache. We defeat that with a
// per-request cache-busting query string plus cache: "no-store", and we surface
// the origin's Last-Modified header as `published_at` so the board can show
// exactly how fresh the bytes are. Next.js route caching is off via
// dynamic = "force-dynamic".
// ───────────────────────────────────────────────────────────────────────────

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export const SCHEDULE_URL = "https://wingdigital26-maker.github.io/schedule/";

export type Meeting = {
  code: string | null;
  title: string;
  short: string;
  days: string;
  start: string;
  end: string;
  bldg: string;
  room: string;
  final: { date?: string; start?: string; end?: string; bldg?: string; room?: string; tba?: boolean } | null;
};

export type SchoolPayload = {
  ok: boolean;
  error?: string;
  source: string;
  fetched_at: string;
  /** Last-Modified reported by the origin for the published page, if given. */
  published_at: string | null;
  label: string | null;
  campus: string | null;
  semester: { start?: string; lastClass?: string; finalsEnd?: string } | null;
  courses: Meeting[];
};

const DATA_BLOCK = /\/\* ==DATA:START== \*\/([\s\S]*?)\/\* ==DATA:END== \*\//;

/**
 * Turn one of build.py's JS object literals into JSON.
 *
 * The block is machine-shaped source (single-quoted strings, bare keys, no
 * expressions), so a narrow transform is enough and is far safer than eval.
 * We deliberately do NOT try to be a general JS parser: if the shape ever
 * changes, JSON.parse throws and the caller reports a parse failure rather
 * than inventing a schedule.
 */
function literalToJson(src: string): unknown {
  let s = src.trim();
  // Strip line comments, but not ones inside a string.
  s = s.replace(/'(?:[^'\\]|\\.)*'|\/\/[^\n]*/g, (m) => (m.startsWith("'") ? m : ""));
  // Single-quoted strings → double-quoted, escaping any inner double quote.
  s = s.replace(/'((?:[^'\\]|\\.)*)'/g, (_m, body: string) => {
    const inner = body.replace(/\\'/g, "'").replace(/"/g, '\\"');
    return `"${inner}"`;
  });
  // Bare object keys → quoted keys (only outside strings, which are now "...").
  s = s.replace(/"(?:[^"\\]|\\.)*"|([{,]\s*)([A-Za-z_$][\w$]*)\s*:/g, (m, pre: string, key: string) =>
    key ? `${pre}"${key}":` : m
  );
  // Trailing commas.
  s = s.replace(/,(\s*[}\]])/g, "$1");
  return JSON.parse(s);
}

function grabLiteral(block: string, name: string): unknown {
  // Match `const NAME = <literal>;` by walking brackets, so nested objects and
  // arrays survive intact.
  const head = new RegExp(`const\\s+${name}\\s*=\\s*`).exec(block);
  if (!head) return null;
  let i = head.index + head[0].length;
  const open = block[i];
  if (open !== "{" && open !== "[") return null;
  const close = open === "{" ? "}" : "]";
  let depth = 0;
  let inStr = false;
  for (; i < block.length; i++) {
    const ch = block[i];
    if (inStr) {
      if (ch === "\\") i++;
      else if (ch === "'") inStr = false;
      continue;
    }
    if (ch === "'") inStr = true;
    else if (ch === open) depth++;
    else if (ch === close) {
      depth--;
      if (depth === 0) {
        const raw = block.slice(head.index + head[0].length, i + 1);
        return literalToJson(raw);
      }
    }
  }
  return null;
}

function str(v: unknown, fallback = ""): string {
  return typeof v === "string" ? v : fallback;
}

function fail(error: string, published_at: string | null = null): SchoolPayload {
  return {
    ok: false,
    error,
    source: SCHEDULE_URL,
    fetched_at: new Date().toISOString(),
    published_at,
    label: null,
    campus: null,
    semester: null,
    courses: [],
  };
}

export async function GET() {
  let res: Response;
  try {
    // Cache-buster: GitHub Pages / Fastly will otherwise hand back up to ten
    // minutes of stale HTML, which is exactly the "live" promise breaking.
    res = await fetch(`${SCHEDULE_URL}?os=${Date.now()}`, {
      cache: "no-store",
      headers: { "Cache-Control": "no-cache", Pragma: "no-cache" },
    });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json(fail(`Could not reach the schedule app (${SCHEDULE_URL}): ${msg}`));
  }

  const published_at = res.headers.get("last-modified");
  if (!res.ok) {
    return NextResponse.json(
      fail(`The schedule app returned HTTP ${res.status} for ${SCHEDULE_URL}.`, published_at)
    );
  }

  const html = await res.text();
  const block = DATA_BLOCK.exec(html);
  if (!block) {
    return NextResponse.json(
      fail(
        "The published schedule page loaded, but it has no DATA block. " +
          "The app's build format changed, so nothing can be read from it.",
        published_at
      )
    );
  }

  let schedule: unknown;
  let semester: unknown;
  let campus: unknown;
  let courses: unknown;
  try {
    schedule = grabLiteral(block[1], "SCHEDULE");
    semester = grabLiteral(block[1], "SEMESTER");
    courses = grabLiteral(block[1], "COURSES");
    const camp = /const\s+CAMPUS\s*=\s*'((?:[^'\\]|\\.)*)'/.exec(block[1]);
    campus = camp ? camp[1].replace(/\\'/g, "'") : null;
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json(
      fail(`The schedule page's DATA block could not be parsed: ${msg}`, published_at)
    );
  }

  if (!Array.isArray(courses)) {
    return NextResponse.json(
      fail("The schedule page's DATA block has no COURSES list.", published_at)
    );
  }

  const parsed: Meeting[] = (courses as Record<string, unknown>[]).map((c) => ({
    code: typeof c.code === "string" ? c.code : null,
    title: str(c.title),
    short: str(c.short) || str(c.title),
    days: str(c.days),
    start: str(c.start),
    end: str(c.end),
    bldg: str(c.bldg),
    room: str(c.room),
    final: c.final && typeof c.final === "object" ? (c.final as Meeting["final"]) : null,
  }));

  const sched = (schedule || {}) as Record<string, unknown>;
  return NextResponse.json({
    ok: true,
    source: SCHEDULE_URL,
    fetched_at: new Date().toISOString(),
    published_at,
    label: typeof sched.label === "string" ? sched.label : null,
    campus: typeof campus === "string" ? campus : null,
    semester: (semester as SchoolPayload["semester"]) ?? null,
    courses: parsed,
  } satisfies SchoolPayload);
}
